# Generated by Django 3.2.12 on 2022-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('Region', models.CharField(max_length=120)),
                ('Catrgory', models.CharField(max_length=120)),
                ('Product', models.CharField(max_length=120)),
                ('city', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
            ],
        ),
    ]
