# Generated by Django 3.2.12 on 2022-10-30 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodsale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodsale',
            old_name='Catrgory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='foodsale',
            old_name='city',
            new_name='Quantity',
        ),
        migrations.AddField(
            model_name='foodsale',
            name='City',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
