# Generated by Django 3.2.12 on 2022-10-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsale', '0002_auto_20221031_0128'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodsale',
            table='foods',
        ),
    ]
